apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  creationTimestamp: null
  name: homarr-route
  namespace: dashboard
spec:
  hostnames:
    - dashboard.apps.k3s.noelmiller.dev
  parentRefs:
    - name: default-gateway
      namespace: cluster-system
      sectionName: https-k3s
  rules:
    - backendRefs:
        - name: homarr
          port: 7575
      matches:
        - path:
            type: PathPrefix
            value: /
