---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: default
  labels:
    app: nginx-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: default
  labels:
    app: nginx-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-web
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gw
  namespace: default
spec:
  gatewayClassName: nginx
  listeners:
    - hostname: nginx.k3s.noelmiller.dev
      name: nginx-k3s-noelmiller-dev-http
      port: 80
      protocol: HTTP
    - hostname: nginx.k3s.noelmiller.dev
      name: nginx-k3s-noelmiller-dev-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: null
            kind: null
            name: default-k3s-wildcard-tls
    - hostname: nginx.noelmiller.dev
      name: nginx-noelmiller-dev-http
      port: 80
      protocol: HTTP
    - hostname: nginx.noelmiller.dev
      name: nginx-noelmiller-dev-https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: null
            kind: null
            name: default-wildcard-tls
status: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: nginx-gw-route-nginx-k3s-noelmiller-dev
  namespace: default
spec:
  hostnames:
    - nginx.k3s.noelmiller.dev
  parentRefs:
    - name: nginx-gw
  rules:
    - backendRefs:
        - name: nginx-web-service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
status:
  parents: []
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  creationTimestamp: null
  name: nginx-gw-route-nginx-noelmiller-dev
  namespace: default
spec:
  hostnames:
    - nginx.noelmiller.dev
  parentRefs:
    - name: nginx-gw
  rules:
    - backendRefs:
        - name: nginx-web-service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
status:
  parents: []
