apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: cluster-system
spec:
  addresses:
    - 10.42.0.11-10.42.0.48 # <--- CHANGE THIS TO YOUR NETWORK RANGE

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: cluster-system
spec:
  ipAddressPools:
    - default-pool
